#!/usr/bin/env python3
"""
Compare A/B/C Nav2 run summaries generated by analyze_nav2_stability_run.py.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _rate_per_min(count: float, duration_sec: float) -> float:
    if duration_sec <= 0:
        return 0.0
    return count * 60.0 / duration_sec


def _anomaly_rate(run: dict[str, Any], key: str) -> float:
    ticks = float(run.get("jsonl", {}).get("ticks", 0))
    value = float(run.get("jsonl", {}).get("anomalies", {}).get(key, 0))
    if ticks <= 0:
        return 0.0
    return value / ticks


def _count(run: dict[str, Any], section: str, key: str) -> float:
    return float(run.get(section, {}).get(key, 0))


def main() -> int:
    parser = argparse.ArgumentParser(description="Compare A/B/C stability summary JSON files.")
    parser.add_argument("--run-a", type=Path, required=True, help="Baseline JSON summary (Run A).")
    parser.add_argument("--run-b", type=Path, help="Robot-only tuning summary (Run B).")
    parser.add_argument("--run-c", type=Path, help="Robot+central tuning summary (Run C).")
    args = parser.parse_args()

    runs = [("A", _load(args.run_a))]
    if args.run_b:
        runs.append(("B", _load(args.run_b)))
    if args.run_c:
        runs.append(("C", _load(args.run_c)))

    print("=== Nav2 Stability Comparison ===")
    print("")
    for label, run in runs:
        dur = float(run.get("duration_sec", 0.0))
        planner_abort = _count(run, "robot", "planner_aborted_action")
        controller_abort = (
            _count(run, "robot", "controller_action_abort")
            + _count(run, "robot", "controller_failed_progress")
            + _count(run, "robot", "controller_patience_exceeded")
        )
        precheck_fail = _count(run, "central", "precheck_timeout") + _count(run, "central", "precheck_aborted")
        goals_reached = _count(run, "central", "goal_reached")

        print(f"[Run {label}] duration={dur:.1f}s")
        print(f"  planner_aborted_per_min: {_rate_per_min(planner_abort, dur):.2f}")
        print(f"  controller_abort_per_min: {_rate_per_min(controller_abort, dur):.2f}")
        print(f"  precheck_fail_per_min: {_rate_per_min(precheck_fail, dur):.2f}")
        print(f"  goals_reached_per_min: {_rate_per_min(goals_reached, dur):.2f}")
        print(f"  plan_stale_rate: {_anomaly_rate(run, 'plan_stale_while_executing'):.3%}")
        print(f"  global_costmap_unavailable_rate: {_anomaly_rate(run, 'global_costmap_unavailable_or_stale'):.3%}")
        print("")

    if len(runs) > 1:
        a = runs[0][1]
        a_dur = float(a.get("duration_sec", 0.0))
        a_planner = _rate_per_min(_count(a, "robot", "planner_aborted_action"), a_dur)
        a_stale = _anomaly_rate(a, "plan_stale_while_executing")
        a_costmap = _anomaly_rate(a, "global_costmap_unavailable_or_stale")

        print("=== Improvement vs Run A ===")
        for label, run in runs[1:]:
            dur = float(run.get("duration_sec", 0.0))
            planner = _rate_per_min(_count(run, "robot", "planner_aborted_action"), dur)
            stale = _anomaly_rate(run, "plan_stale_while_executing")
            costmap = _anomaly_rate(run, "global_costmap_unavailable_or_stale")
            planner_delta = ((a_planner - planner) / a_planner * 100.0) if a_planner > 0 else 0.0
            stale_delta = ((a_stale - stale) / a_stale * 100.0) if a_stale > 0 else 0.0
            costmap_delta = ((a_costmap - costmap) / a_costmap * 100.0) if a_costmap > 0 else 0.0
            print(f"Run {label}: planner {planner_delta:+.1f}%, stale {stale_delta:+.1f}%, costmap_unavail {costmap_delta:+.1f}%")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

