#!/usr/bin/env bash
# Use on the ROBOT to set ROS_DOMAIN_ID and Fast DDS profile for talking to the central PC.
# Source in the robot shell before: ros2 launch turtlebot3_bringup robot.launch.py
#
#   source scripts/set_robot_env.sh blinky
#   source scripts/set_robot_env.sh blinky 192.168.50.108
#
# With no central IP: uses scripts/fastdds_initial_peers_robot.xml (edit that file to set central IP).
# With central IP: writes a generated profile and uses it (no need to edit the static XML).

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-.}")" && pwd)"
_TURTLEBOT3_WS="$(cd "${_SCRIPT_DIR}/.." && pwd)"
_GENERATED_XML="${_SCRIPT_DIR}/.fastdds_initial_peers_robot_generated.xml"

set_robot_env_robot_usage() {
  echo "Usage: source scripts/set_robot_env.sh <robot> [central_ip]"
  echo ""
  echo "  robot      One of: blinky, pinky, inky, clyde"
  echo "  central_ip Optional. Central PC's IP on the robot's subnet (e.g. 192.168.50.108)."
  echo "             If omitted, uses scripts/fastdds_initial_peers_robot.xml (edit that file for central IP)."
  echo ""
  echo "  Robot   ROS_DOMAIN_ID"
  echo "  ------  -------------"
  echo "  Blinky  30"
  echo "  Pinky   31"
  echo "  Inky    32"
  echo "  Clyde   33"
}

robot=$(echo "${1:-}" | tr '[:upper:]' '[:lower:]')
central_ip="${2:-}"

case "$robot" in
  blinky)
    export ROS_DOMAIN_ID=30
    ;;
  pinky)
    export ROS_DOMAIN_ID=31
    ;;
  inky)
    export ROS_DOMAIN_ID=32
    ;;
  clyde)
    export ROS_DOMAIN_ID=33
    ;;
  "")
    set_robot_env_robot_usage
    return 1 2>/dev/null || exit 1
    ;;
  -h|--help)
    set_robot_env_robot_usage
    return 0 2>/dev/null || exit 0
    ;;
  *)
    echo "Unknown robot: $1"
    set_robot_env_robot_usage
    return 1 2>/dev/null || exit 1
    ;;
esac

export TURTLEBOT3_MODEL=burger
export LDS_MODEL=LDS-02

if [[ -n "$central_ip" ]]; then
  # Generate XML with the given central IP and all domain ports (30,31,32,33)
  cat > "${_GENERATED_XML}" << EOF
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by set_robot_env_robot.sh: central $central_ip, robot $robot (ROS_DOMAIN_ID=$ROS_DOMAIN_ID) -->
<dds>
  <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <participant profile_name="initial_peers_robot" is_default_profile="true">
      <rtps>
        <builtin>
          <initialPeersList>
            <locator><udpv4><address>${central_ip}</address><port>14910</port></udpv4></locator>
            <locator><udpv4><address>${central_ip}</address><port>14912</port></udpv4></locator>
            <locator><udpv4><address>${central_ip}</address><port>15160</port></udpv4></locator>
            <locator><udpv4><address>${central_ip}</address><port>15162</port></udpv4></locator>
            <locator><udpv4><address>${central_ip}</address><port>15410</port></udpv4></locator>
            <locator><udpv4><address>${central_ip}</address><port>15412</port></udpv4></locator>
            <locator><udpv4><address>${central_ip}</address><port>15660</port></udpv4></locator>
            <locator><udpv4><address>${central_ip}</address><port>15662</port></udpv4></locator>
          </initialPeersList>
        </builtin>
      </rtps>
    </participant>
  </profiles>
</dds>
EOF
  export FASTRTPS_DEFAULT_PROFILES_FILE="${_GENERATED_XML}"
  echo "Robot: $robot  ROS_DOMAIN_ID=$ROS_DOMAIN_ID  central=$central_ip  (generated profile)"
else
  export FASTRTPS_DEFAULT_PROFILES_FILE="${_TURTLEBOT3_WS}/scripts/fastdds_initial_peers_robot.xml"
  echo "Robot: $robot  ROS_DOMAIN_ID=$ROS_DOMAIN_ID  (using scripts/fastdds_initial_peers_robot.xml — set central IP in that file if needed)"
fi